(function(){
'use strict';
const TOTAL=QUESTIONS.length,tracked=new Set();
const t=key=>window.i18n?window.i18n.t(key):key;
function track(stage){if(tracked.has(stage))return;tracked.add(stage);if(typeof window.gtag==='function')window.gtag('event',`mbti_love_${stage}`,{event_category:'relationship_preference_reflection'})}
class PreferenceReflection{
  constructor(){this.index=0;this.scores={E:0,I:0,S:0,N:0,T:0,F:0,J:0,P:0};this.first={};this.locked=false;this.bind();Promise.resolve(window.i18n.ready).finally(()=>{document.getElementById('app-loader')?.remove();this.syncRoutes();track('view')})}
  bind(){document.getElementById('btn-start').addEventListener('click',()=>this.start());document.getElementById('btn-retry').addEventListener('click',()=>this.retry());document.getElementById('share-page').addEventListener('click',()=>this.share());document.getElementById('next-action').addEventListener('click',()=>track('next_click'));document.querySelectorAll('[data-related-slug]').forEach(link=>link.addEventListener('click',()=>track('related_click')));this.bindTheme();this.bindLanguage()}
  bindTheme(){const button=document.getElementById('theme-toggle');if(localStorage.getItem('mbti-love-theme')==='light')document.documentElement.dataset.theme='light';const update=()=>button.textContent=document.documentElement.dataset.theme==='light'?'☀':'☾';update();button.addEventListener('click',()=>{const light=document.documentElement.dataset.theme!=='light';if(light)document.documentElement.dataset.theme='light';else delete document.documentElement.dataset.theme;localStorage.setItem('mbti-love-theme',light?'light':'dark');update()})}
  bindLanguage(){const toggle=document.getElementById('lang-toggle'),menu=document.getElementById('lang-menu');toggle.addEventListener('click',()=>{menu.hidden=!menu.hidden;toggle.setAttribute('aria-expanded',String(!menu.hidden))});menu.querySelectorAll('[data-lang]').forEach(button=>button.addEventListener('click',async()=>{await window.i18n.setLanguage(button.dataset.lang);menu.hidden=true;toggle.setAttribute('aria-expanded','false');this.syncRoutes();if(document.getElementById('question-screen').classList.contains('active'))this.renderQuestion();if(document.getElementById('result-screen').classList.contains('active'))this.renderResult()}));document.addEventListener('click',event=>{if(!event.target.closest('.language-selector')){menu.hidden=true;toggle.setAttribute('aria-expanded','false')}})}
  lang(){return window.i18n.getCurrentLanguage()}
  syncRoutes(){const lang=this.lang();document.getElementById('next-action').href=`/mbti-love/deck.html?lang=${lang}&source=mbti_love_result`;document.querySelector('[data-related-slug="attachment-style"]').href=`/attachment-style/?lang=${lang}&source=mbti_love_related`;document.querySelector('[data-related-slug="love-language"]').href=`/love-language/?lang=${lang}&source=mbti_love_related`}
  show(id){document.querySelectorAll('.screen').forEach(screen=>screen.classList.toggle('active',screen.id===id));window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}
  reset(){this.index=0;for(const key of Object.keys(this.scores))this.scores[key]=0;this.first={};this.locked=false}
  start(){this.reset();track('start');this.show('question-screen');this.renderQuestion()}
  renderQuestion(){const question=QUESTIONS[this.index];document.getElementById('progress-text').textContent=`${this.index+1} / ${TOTAL}`;document.getElementById('progress-fill').style.width=`${((this.index+1)/TOTAL)*100}%`;document.getElementById('q-text').textContent=t(`questions.${question.textKey}`);const options=document.getElementById('q-options');options.replaceChildren();question.options.forEach(option=>{const button=document.createElement('button');button.type='button';button.className='option';button.textContent=t(`questions.${option.textKey}`);button.addEventListener('click',()=>this.answer(option));options.append(button)})}
  answer(option){if(this.locked)return;this.locked=true;document.querySelectorAll('.option').forEach(button=>button.disabled=true);this.scores[option.val]+=1;if(!this.first[option.dim])this.first[option.dim]=option.val;this.index+=1;if(this.index===6)track('progress');setTimeout(()=>{this.locked=false;if(this.index<TOTAL)this.renderQuestion();else this.finish()},120)}
  result(){return AXES.map(axis=>{const[left,right]=axis;return this.scores[left]===this.scores[right]?this.first[axis]:(this.scores[left]>this.scores[right]?left:right)}).join('')}
  finish(){this.show('result-screen');this.renderResult();track('complete')}
  renderResult(){const code=this.result();document.getElementById('r-type').textContent=code;const list=document.getElementById('axis-list');list.replaceChildren();code.split('').forEach(letter=>{const item=document.createElement('div');item.className='axis-item';const badge=document.createElement('b');badge.textContent=letter;const copy=document.createElement('div'),title=document.createElement('strong'),body=document.createElement('p');title.textContent=t(`axis.${letter}.title`);body.textContent=t(`axis.${letter}.body`);copy.append(title,body);item.append(badge,copy);list.append(item)});document.getElementById('share-status').textContent='';this.syncRoutes()}
  async share(){const data={title:document.title,text:t('share.text'),url:'https://dopabrain.com/mbti-love/'};let success=false;try{if(navigator.share){await navigator.share(data);success=true}else if(navigator.clipboard){await navigator.clipboard.writeText(data.url);success=true}}catch(error){if(error&&error.name==='AbortError')return}document.getElementById('share-status').textContent=success?t('share.success'):t('share.failure');if(success)track('share')}
  retry(){this.reset();this.show('intro-screen')}
}
window.mbtiLoveApp=new PreferenceReflection();
})();
